# Generated by Django 4.0.4 on 2022-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tasks_endreportdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='fileName',
            field=models.TextField(null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reportContetn',
            field=models.BinaryField(null=True, verbose_name='Отчет'),
        ),
    ]
