# Generated by Django 4.0.4 on 2022-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_tasks_filename_alter_tasks_reportcontetn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='endReportDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='fileName',
            field=models.TextField(blank=True, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reportContetn',
            field=models.BinaryField(blank=True, null=True, verbose_name='Отчет'),
        ),
    ]
