# Generated by Django 4.0.4 on 2022-05-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_tasks_endreportdatetime_alter_tasks_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='startReportDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запуска'),
        ),
    ]
