# Generated by Django 4.0.4 on 2022-05-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_tasks_startreportdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='startReportDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время запуска'),
        ),
    ]
