# Generated by Django 4.0.4 on 2022-05-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_tasks_startreportdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='state',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='webapp.states', verbose_name='Статус'),
        ),
    ]
