# Generated by Django 4.0.4 on 2022-05-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_alter_tasks_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemName', models.CharField(max_length=50, unique=True, verbose_name='Системное имя отчетной формы')),
                ('name', models.CharField(max_length=250, verbose_name='Имя отчета на русском языке')),
                ('parametr', models.TextField(verbose_name='Параметры формирования отчета')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reportCode',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reportName',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='userLogin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, сформировавший запрос'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapp.report', verbose_name='Отчет'),
            preserve_default=False,
        ),
    ]
