# Generated by Django 4.0.4 on 2022-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_report_remove_tasks_reportcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['systemName'], 'verbose_name': 'Отчетная форма', 'verbose_name_plural': 'Отчетные формы'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='errorMsg',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
